USE ROLE ACCOUNTADMIN;
SET USERNAME = (SELECT CURRENT_USER());
CREATE OR REPLACE ROLE MLOPS_ROLE;

-- Grant necessary permissions to create databases, compute pools, and service endpoints to new role
GRANT CREATE DATABASE on ACCOUNT to ROLE MLOPS_ROLE; 
GRANT CREATE COMPUTE POOL on ACCOUNT to ROLE MLOPS_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT to ROLE MLOPS_ROLE;
GRANT BIND SERVICE ENDPOINT on ACCOUNT to ROLE MLOPS_ROLE;

-- grant new role to user and switch to that role
GRANT ROLE MLOPS_ROLE to USER identifier($USERNAME);
USE ROLE MLOPS_ROLE;

-- Create warehouse
CREATE OR REPLACE WAREHOUSE MLOPS_WH WITH WAREHOUSE_SIZE='SMALL';

-- Create Database 
CREATE OR REPLACE DATABASE MLOPS_DB;

-- Create Schema
CREATE OR REPLACE SCHEMA MLOPS_SCHEMA;

-- Create compute pool
CREATE COMPUTE POOL IF NOT EXISTS MLOPS_COMPUTE_POOL 
 MIN_NODES = 1
 MAX_NODES = 1
 INSTANCE_FAMILY = CPU_X64_M;

-- Describe compute pool
DESCRIBE COMPUTE POOL MLOPS_COMPUTE_POOL;

-- Create notebook 
CREATE OR REPLACE NOTEBOOK MLOPS_DB.MLOPS_SCHEMA.MLOPS_NB 
MAIN_FILE = 'Snowflake_ML_Loans.ipynb' 
QUERY_WAREHOUSE = MLOPS_WH
RUNTIME_NAME = 'SYSTEM$BASIC_RUNTIME' 
COMPUTE_POOL = 'MLOPS_COMPUTE_POOL'
IDLE_AUTO_SHUTDOWN_TIME_SECONDS = 3600;

CREATE STAGE IF NOT EXISTS MLOPS_DB.MLOPS_SCHEMA.MLOPS_STAGE
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = (TYPE = 'CSV');  
